//! scheduler.h / OSLikeStuff `scheduler_api.h` — the cooperative task scheduler,
//! implemented on top of the Embassy executor (the "Stage 2" design from
//! `include/libdeluge/scheduler.h`).
//!
//! On the bare-metal / host BSPs this C ABI is backed by the C++ `TaskManager`
//! (`src/OSLikeStuff/task_scheduler/`), a single-stack cooperative scheduler with
//! a deadline-aware priority heuristic. On the Embassy BSP we instead **decompose**
//! each registered Deluge task into its own Embassy task: `addRepeatingTask` claims
//! a [`TaskSlot`] and spawns a [`task_runner`] instance that wakes on an
//! `embassy_time` timer, runs the (synchronous, run-to-completion) C++ handle, and
//! loops. The Embassy executor *is* the scheduler loop; there is no `TaskManager`
//! on this BSP (its translation units drop out of the static-archive link because
//! the C ABI symbols below satisfy every reference — see build.rs).
//!
//! The deadline-aware priority heuristic (`chooseBestTask`) is intentionally not
//! reproduced: Embassy round-robins ready tasks, audio is lifted onto an
//! interrupt-driven path (so it cannot be starved regardless of cadence), and the
//! remaining tasks are paced by their `targetTimeBetweenCalls`.
//!
//! Concurrency model: the executor is single-threaded (`executor-thread`), so the
//! C-ABI entry points (called synchronously from the C++ app on the executor
//! thread) and the task runners never race each other; the only other contexts are
//! ISRs, which touch nothing here. The atomics below are for `static` interior
//! mutability and ABI cleanliness, not cross-core synchronisation.
#![allow(non_snake_case)]

use core::sync::atomic::{AtomicBool, AtomicI8, AtomicU64, AtomicUsize, Ordering};

use embassy_executor::{SendSpawner, Spawner};
use embassy_futures::select::{Either, select};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use embassy_sync::signal::Signal;
use embassy_time::{Duration, Instant, Timer};

// `RunCondition` is a bindgen type (`crate::sys`, device-only — no C++ ABI is
// linked on host). On host, reuse the identical host stand-in `fiber.rs`
// already defines for the same C typedef (`storage_wait.h`), keeping the
// scheduler's logic (this file) untouched — only the type's source differs.
#[cfg(not(target_os = "none"))]
use crate::fiber::RunCondition;
#[cfg(target_os = "none")]
use crate::sys::RunCondition;

// ---------------------------------------------------------------------------
// C-ABI types (scheduler_api.h). Not generated by bindgen: the canonical header
// `<libdeluge/scheduler.h>` forwards to OSLikeStuff via a relative include that
// does not resolve under bindgen's include path, so wrapper.h omits it. These are
// trivial, stable C types; define them here. `RunCondition` *is* generated (via
// storage_wait.h) so we reuse it to keep the predicate type identical.
// ---------------------------------------------------------------------------

/// `void (*)()` — a task body. Always non-null from the C++ side.
type TaskHandle = extern "C" fn();
/// `int8_t` task id == the [`SLOTS`] index, matching the C++ ABI exactly.
type TaskID = i8;
/// `uint32_t` resource bitmask (RESOURCE_SD / RESOURCE_USB / RESOURCE_SD_ROUTINE).
type ResourceID = u32;

const RESOURCE_NONE: ResourceID = 0;
/// Slow-storage (SD/MMC, SPI flash) — `scheduler_api.h` RESOURCE_SD.
const RESOURCE_SD: ResourceID = 1;
/// USB transport — `scheduler_api.h` RESOURCE_USB.
const RESOURCE_USB: ResourceID = 2;
/// "Must not run inside an SD routine" — `scheduler_api.h` RESOURCE_SD_ROUTINE.
/// Approximated here by gating on the SD mutex (held across any SD task's handle),
/// which is the only SD_ROUTINE user (the one-shot startup-song task) needs.
const RESOURCE_SD_ROUTINE: ResourceID = 4;

// ABI guard: these must match scheduler_api.h's `typedef`s exactly, or the C++
// side reads/writes ids and resources at the wrong width across the boundary.
const _: () = {
    assert!(core::mem::size_of::<TaskID>() == 1, "TaskID must be int8_t");
    assert!(
        core::mem::size_of::<ResourceID>() == 4,
        "ResourceID must be uint32_t"
    );
    assert!(
        core::mem::size_of::<TaskHandle>() == core::mem::size_of::<usize>(),
        "TaskHandle must be pointer-sized"
    );
};

/// Maximum concurrently-live tasks. Mirrors `TaskManager::kMaxTasks` so the slot
/// table and the Embassy task pool below match the C++ scheduler's capacity.
/// NOTE: kept in lock-step with the `task_runner` `pool_size` literal (the task
/// macro wants a literal); the const-assert below guards against drift.
const MAX_TASKS: usize = 25;
const _: () = assert!(
    MAX_TASKS == 25,
    "task_runner pool_size literal must equal MAX_TASKS"
);

/// How often a conditional task re-evaluates its `RunCondition` while waiting. The
/// C++ scheduler checks conditionals on every idle pass; a few-ms poll is plenty
/// (the only conditional in `registerTasks` is the one-shot startup-song task).
const COND_POLL: Duration = Duration::from_millis(4);

// ---------------------------------------------------------------------------
// Task slot: per-task control block. One Embassy task runner instance owns each
// in-use slot for its lifetime; the C-ABI control functions (block/unblock/boost/
// remove/run/setNextRunTime) poke these fields and wake the runner via `wake`.
// ---------------------------------------------------------------------------

struct TaskSlot {
    /// Claimed by `add*Task`, released when the runner returns.
    used: AtomicBool,
    /// `TaskHandle` as a `usize` (transmuted on call). 0 only before first use.
    handle: AtomicUsize,
    /// `RunCondition` as a `usize`, or 0 for none (repeating/once tasks).
    condition: AtomicUsize,
    /// Target time between calls, microseconds (repeating); or the one-shot delay
    /// (once). Conditional tasks ignore this and poll `condition` instead.
    period_us: AtomicU64,
    /// Minimum time from completion to the next call, microseconds.
    backoff_us: AtomicU64,
    /// Resource bitmask gating the run (these will map onto embassy-sync
    /// mutexes; today the gate is a no-op).
    resource: AtomicU64,
    /// Run once then free (once / conditional tasks).
    once: AtomicBool,
    /// `blockTask`/`unblockTask`: when false the runner parks on `wake`.
    enabled: AtomicBool,
    /// `boostTask`: run the next cycle 10x sooner (one-shot, cleared after use).
    boosted: AtomicBool,
    /// `removeTask`: runner exits its loop and frees the slot.
    stop: AtomicBool,
    /// `setNextRunTimeforCurrentTask`: override the next wait (µs); 0 = no override.
    next_override_us: AtomicU64,
    /// Exclude from `printStats`-style accounting.
    count_stats: AtomicBool,
    /// Running-average run time, microseconds (halving filter, matching the C++
    /// `StatBlock`: avg = (avg + sample) / 2).
    avg_run_us: AtomicU64,
    /// Wakes the runner early (runTask / unblockTask / removeTask / boost).
    wake: Signal<CriticalSectionRawMutex, ()>,
}

impl TaskSlot {
    const fn new() -> Self {
        TaskSlot {
            used: AtomicBool::new(false),
            handle: AtomicUsize::new(0),
            condition: AtomicUsize::new(0),
            period_us: AtomicU64::new(0),
            backoff_us: AtomicU64::new(0),
            resource: AtomicU64::new(RESOURCE_NONE as u64),
            once: AtomicBool::new(false),
            enabled: AtomicBool::new(true),
            boosted: AtomicBool::new(false),
            stop: AtomicBool::new(false),
            next_override_us: AtomicU64::new(0),
            count_stats: AtomicBool::new(true),
            avg_run_us: AtomicU64::new(0),
            wake: Signal::new(),
        }
    }

    fn handle_fn(&self) -> TaskHandle {
        // SAFETY: written only by `claim` from a real `TaskHandle`; the runner
        // never calls a slot whose handle is unset.
        unsafe { core::mem::transmute::<usize, TaskHandle>(self.handle.load(Ordering::Relaxed)) }
    }

    /// The stored predicate, or `None` for repeating/once tasks. `RunCondition` is
    /// itself `Option<fn>`, so a 0 (unset) word transmutes straight to `None`.
    fn condition_fn(&self) -> RunCondition {
        // SAFETY: written only by `claim` from a real `RunCondition` (or 0 = None).
        unsafe {
            core::mem::transmute::<usize, RunCondition>(self.condition.load(Ordering::Relaxed))
        }
    }

    /// Microseconds to wait before the next run, consuming one-shot overrides.
    fn next_wait_us(&self) -> u64 {
        let override_us = self.next_override_us.swap(0, Ordering::Relaxed);
        let base = if override_us != 0 {
            override_us
        } else {
            self.period_us.load(Ordering::Relaxed)
        };
        if self.boosted.swap(false, Ordering::Relaxed) {
            base / 10
        } else {
            base
        }
    }

    fn record(&self, run_us: u64) {
        if !self.count_stats.load(Ordering::Relaxed) {
            return;
        }
        let avg = self.avg_run_us.load(Ordering::Relaxed);
        // Halving filter, matching C++ StatBlock::update.
        self.avg_run_us.store((avg + run_us) / 2, Ordering::Relaxed);
    }

    fn reset_for_reuse(&self) {
        self.condition.store(0, Ordering::Relaxed);
        self.period_us.store(0, Ordering::Relaxed);
        self.backoff_us.store(0, Ordering::Relaxed);
        self.resource.store(RESOURCE_NONE as u64, Ordering::Relaxed);
        self.once.store(false, Ordering::Relaxed);
        self.enabled.store(true, Ordering::Relaxed);
        self.boosted.store(false, Ordering::Relaxed);
        self.stop.store(false, Ordering::Relaxed);
        self.next_override_us.store(0, Ordering::Relaxed);
        self.count_stats.store(true, Ordering::Relaxed);
        self.avg_run_us.store(0, Ordering::Relaxed);
        // Drain any stale wake so a freshly-claimed slot doesn't fire immediately.
        self.wake.reset();
    }
}

/// The task table. `static` (not `static mut`): every field is interior-mutable
/// and `Sync`, so `&'static TaskSlot` references handed to runners are sound.
static SLOTS: [TaskSlot; MAX_TASKS] = [const { TaskSlot::new() }; MAX_TASKS];

/// Index of the slot whose handle is currently executing, for the
/// `*ForCurrentTask` C-ABI calls. -1 when no handle is running.
static CURRENT: AtomicI8 = AtomicI8::new(-1);

/// Resource gate (RESOURCE_USB). A task holding it in its schedule acquires the
/// gate for the duration of its (synchronous) handle, so two same-resource tasks
/// can't run concurrently. Audio (RESOURCE_NONE) never touches this, so the
/// audio interrupt-executor never blocks on it.
///
/// There is no equivalent RESOURCE_SD gate: that serialization is now provided
/// by the single-owner storage discipline (the storage owner IS the worker
/// fiber; see `deluge_storage_on_owner` in sd.rs and the `storage-owner-audit`
/// feature) plus the rung-5 `block_on_fiber` flip in sd.rs, which yields the
/// fiber mid-transfer instead of parking the executor. `SD_GATE` served that
/// purpose in the run-to-completion staging model and has been retired now
/// that the real mechanism is live. `RESOURCE_SD_ROUTINE` tasks still get a
/// hold-off, but via `fiber::sd_routine_held()` below, not a gate.
static USB_GATE: Mutex<CriticalSectionRawMutex, ()> = Mutex::new(());

// ---------------------------------------------------------------------------
// Spawner stash. The executor closure in `main` calls [`set_spawner`] before the
// C++ app's `deluge_app_init` runs `registerTasks()`, so the `add*Task` entry
// points (invoked synchronously on the executor thread) can spawn runners.
// Sound because the executor is single-threaded: only that thread ever touches it.
// ---------------------------------------------------------------------------
static mut SPAWNER: Option<Spawner> = None;

/// Spawner for the preemptive audio interrupt-executor (`AUDIO_EXEC` in main).
/// `SendSpawner` because that executor runs in a different context (the SGI). The
/// priority-0 (audio) task is routed here so it preempts the thread executor.
static mut AUDIO_SPAWNER: Option<SendSpawner> = None;

/// Stash the executor's spawner so the C-ABI `add*Task` functions can spawn task
/// runners. Call once, from inside `executor.run(|spawner| ...)`, before
/// `deluge_app_init`.
pub fn set_spawner(spawner: Spawner) {
    // SAFETY: single-threaded executor; called once at startup before any task
    // runs, and only ever read on the same thread.
    unsafe { *core::ptr::addr_of_mut!(SPAWNER) = Some(spawner) };
}

/// Stash the audio interrupt-executor's spawner (from `InterruptExecutor::start`).
/// Call once at startup, before `deluge_app_init`.
pub fn set_audio_spawner(spawner: SendSpawner) {
    // SAFETY: set once at startup before any task runs.
    unsafe { *core::ptr::addr_of_mut!(AUDIO_SPAWNER) = Some(spawner) };
}

fn spawner() -> Option<Spawner> {
    // SAFETY: see `set_spawner`; reads happen only on the executor thread.
    unsafe { *core::ptr::addr_of!(SPAWNER) }
}

fn audio_spawner() -> Option<SendSpawner> {
    // SAFETY: set once at startup; SendSpawner is Copy + Send.
    unsafe { *core::ptr::addr_of!(AUDIO_SPAWNER) }
}

/// Lens-1-only (deterministic virtual-time streaming-underrun harness, Task 7)
/// override for the priority-0 (audio) task's schedule. `AudioEngine::routine_task`'s
/// registered period (`deluge.cpp`: `8 / 44100.` seconds) is a scheduler poll/backoff
/// hint tuned for the DEVICE's real DMA-paced render throttling
/// (`AudioEngine::routine` decides internally whether a new block is actually due,
/// based on the free-running DMA play head) — the host null-sink render pump
/// (`audio_host.rs`'s `deluge_audio_drive`) has no such throttling and renders
/// exactly one block every call, so on host the REGISTERED period does not
/// correspond to "one real-time block period" at all (it fires ~1.6ms apart, vs.
/// the true 128/44100s ≈ 2.9ms block period). Lens 1's virtual-time race needs the
/// audio consumer to advance in a KNOWN, exact per-block virtual-time increment to
/// make the SD-latency race meaningful, so it overrides the audio slot's
/// `period_us`/`backoff_us` at spawn time via this knob. `None` (unset, the
/// default) preserves today's behavior for every other consumer (device, Lens 2,
/// manual host_app runs) — see [`claim`]'s use of this below. Host-only: the whole
/// mechanism is `#[cfg(not(target_os = "none"))]`, so it costs the device build
/// nothing (not even a dead branch).
#[cfg(not(target_os = "none"))]
static AUDIO_PERIOD_OVERRIDE_US: AtomicU64 = AtomicU64::new(0);
#[cfg(not(target_os = "none"))]
static AUDIO_BACKOFF_OVERRIDE_US: AtomicU64 = AtomicU64::new(0);
#[cfg(not(target_os = "none"))]
static AUDIO_OVERRIDE_SET: AtomicBool = AtomicBool::new(false);

/// See [`AUDIO_PERIOD_OVERRIDE_US`]'s doc comment. Call once at startup, before
/// `deluge_app_init` runs `registerTasks()` (i.e. before the audio task is
/// claimed).
#[cfg(not(target_os = "none"))]
pub fn set_audio_period_override_us(period_us: u64, backoff_us: u64) {
    AUDIO_PERIOD_OVERRIDE_US.store(period_us, Ordering::Relaxed);
    AUDIO_BACKOFF_OVERRIDE_US.store(backoff_us, Ordering::Relaxed);
    AUDIO_OVERRIDE_SET.store(true, Ordering::Relaxed);
}

/// Claim a free slot, populate it, and spawn its runner. Returns the slot index as
/// the `TaskID`, or -1 if the table is full or the spawner is unavailable.
fn claim(
    handle: TaskHandle,
    condition: RunCondition,
    period_us: u64,
    backoff_us: u64,
    resource: ResourceID,
    once: bool,
    enabled: bool,
    on_audio: bool,
) -> TaskID {
    // Lens 1 only: substitute the virtual-time block-period override for the
    // audio task's registered schedule — see `AUDIO_PERIOD_OVERRIDE_US`'s doc
    // comment. A no-op (`period_us`/`backoff_us` pass through unchanged) unless
    // `set_audio_period_override_us` was called, which only Lens 1 ever does.
    #[cfg(not(target_os = "none"))]
    let (period_us, backoff_us) = if on_audio && AUDIO_OVERRIDE_SET.load(Ordering::Relaxed) {
        (
            AUDIO_PERIOD_OVERRIDE_US.load(Ordering::Relaxed),
            AUDIO_BACKOFF_OVERRIDE_US.load(Ordering::Relaxed),
        )
    } else {
        (period_us, backoff_us)
    };

    // Route the audio task to the preemptive audio interrupt-executor when it's
    // available; everything else (and audio, if that executor isn't up) runs on
    // the cooperative thread executor.
    let use_audio = on_audio && audio_spawner().is_some();
    if !use_audio && spawner().is_none() {
        return -1;
    }
    for (i, slot) in SLOTS.iter().enumerate() {
        if slot
            .used
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Relaxed)
            .is_ok()
        {
            slot.reset_for_reuse();
            slot.handle.store(handle as usize, Ordering::Relaxed);
            slot.condition
                .store(condition.map_or(0, |c| c as usize), Ordering::Relaxed);
            slot.period_us.store(period_us, Ordering::Relaxed);
            slot.backoff_us.store(backoff_us, Ordering::Relaxed);
            slot.resource.store(resource as u64, Ordering::Relaxed);
            slot.once.store(once, Ordering::Relaxed);
            slot.enabled.store(enabled, Ordering::Relaxed);
            // The task macro yields a `Result<SpawnToken, _>` (pool allocation);
            // `Err` means the pool (== MAX_TASKS) is exhausted.
            let Ok(token) = task_runner(slot) else {
                slot.used.store(false, Ordering::Release);
                return -1;
            };
            if use_audio {
                // SendSpawner: the audio executor runs in the SGI context.
                audio_spawner().unwrap().spawn(token);
            } else {
                spawner().unwrap().spawn(token);
            }
            return i as TaskID;
        }
    }
    -1
}

fn slot_of(id: TaskID) -> Option<&'static TaskSlot> {
    let i = id as isize;
    if i < 0 || i as usize >= MAX_TASKS {
        return None;
    }
    let slot = &SLOTS[i as usize];
    slot.used.load(Ordering::Acquire).then_some(slot)
}

fn current_slot() -> Option<&'static TaskSlot> {
    slot_of(CURRENT.load(Ordering::Relaxed))
}

/// Count of currently-claimed slots — i.e. how many `add*Task` calls have
/// landed and not yet been removed. `host_app`-only: the boot-and-idle smoke
/// (`main.rs`) polls this from a second thread as the cheapest strong signal
/// that the real C++ app's `registerTasks()` actually ran (it calls
/// `addRepeatingTask`/`addConditionalTask` a couple dozen times during
/// `deluge_app_init`), rather than just that BSP init reached that point.
#[cfg(all(not(target_os = "none"), feature = "host_app"))]
pub fn registered_task_count() -> usize {
    SLOTS
        .iter()
        .filter(|s| s.used.load(Ordering::Acquire))
        .count()
}

/// One Embassy task per Deluge task. Pool sized to [`MAX_TASKS`] so every slot can
/// be live at once. Waits per the slot's schedule (or condition), runs the C++
/// handle to completion, and loops until removed or (for once tasks) it has run.
#[embassy_executor::task(pool_size = 25)]
async fn task_runner(slot: &'static TaskSlot) {
    // Acquire-pair with `claim`'s store of `used`/handle so we observe them.
    while !slot.used.load(Ordering::Acquire) {
        embassy_futures::yield_now().await;
    }

    loop {
        if slot.stop.load(Ordering::Relaxed) {
            break;
        }
        if !slot.enabled.load(Ordering::Relaxed) {
            // Blocked: park until unblockTask/runTask/removeTask signals us.
            slot.wake.wait().await;
            continue;
        }

        match slot.condition_fn() {
            Some(cond) => {
                // Conditional task: poll the predicate, then run once.
                // SAFETY: `cond` is the C++ app's predicate; calling it is benign.
                while !unsafe { cond() } {
                    if slot.stop.load(Ordering::Relaxed) {
                        slot.used.store(false, Ordering::Release);
                        return;
                    }
                    Timer::after(COND_POLL).await;
                }
            }
            None => {
                // Timed task: wait the (possibly boosted/overridden) interval, but
                // wake early on an explicit signal (runTask / unblock / remove).
                let wait = Duration::from_micros(slot.next_wait_us());
                if let Either::Second(()) = select(Timer::after(wait), slot.wake.wait()).await {
                    // Signalled: re-evaluate stop/enabled at the top of the loop.
                    continue;
                }
            }
        }

        if slot.stop.load(Ordering::Relaxed) {
            break;
        }
        if !slot.enabled.load(Ordering::Relaxed) {
            continue;
        }

        let resource = slot.resource.load(Ordering::Relaxed) as ResourceID;

        // Hold off RESOURCE_SD_ROUTINE tasks while an SD-routine op is in flight on
        // the worker (fiber.rs SD_ROUTINE_HELD). Mirrors the cooperative BSP's
        // isSDRoutineActive() gate: a task that would free an object such an op is
        // mid-way through (discardRecorder freeing the recorder) must not run. Live
        // (not inert) now that the rung-5 flip (sd.rs `block_on_fiber`) makes SD
        // transfers actually yield: the counter lingers across the whole in-flight
        // window, not just a synchronous run-to-completion instant, so this is the
        // real hold-off — independent of (and unaffected by) `SD_GATE`'s retirement.
        if resource & RESOURCE_SD_ROUTINE != 0 && crate::fiber::sd_routine_held() {
            continue;
        }

        // Acquire the resource gate(s) the schedule asks for, held across the
        // (synchronous) handle so same-resource tasks can't overlap. (RESOURCE_SD
        // has no gate here — see the comment on `USB_GATE` above.)
        let run_us = {
            let _usb = if resource & RESOURCE_USB != 0 {
                Some(USB_GATE.lock().await)
            } else {
                None
            };

            // Set CURRENT for the *ForCurrentTask C-ABI calls, saving/restoring the
            // previous value: the audio interrupt-executor can preempt a thread-mode
            // task_runner mid-handle, and must leave CURRENT as it found it so the
            // preempted task's id is intact when it resumes.
            let idx = SLOTS.iter().position(|s| core::ptr::eq(s, slot)).unwrap() as TaskID;
            let prev = CURRENT.swap(idx, Ordering::Relaxed);
            let t0 = Instant::now();
            (slot.handle_fn())();
            let run_us = t0.elapsed().as_micros();
            CURRENT.store(prev, Ordering::Relaxed);
            run_us
            // _usb gate released here, before the once-check and back-off.
        };
        slot.record(run_us);

        // This task just made progress; if a worker-fiber op is suspended on a
        // predicate that depends on it (cluster drain, button release, playback
        // stop, ...), wake the pump to re-check. No-op when the worker is idle.
        crate::fiber::wake_if_busy();

        if slot.once.load(Ordering::Relaxed) {
            break;
        }

        // Back-off: never re-run sooner than backoff_us after completion.
        let backoff = slot.backoff_us.load(Ordering::Relaxed);
        if backoff != 0 {
            Timer::after(Duration::from_micros(backoff)).await;
        }
    }

    slot.used.store(false, Ordering::Release);
}

// ---------------------------------------------------------------------------
// Helpers for the seconds<->microseconds C ABI (the API speaks `double` seconds).
// ---------------------------------------------------------------------------

fn secs_to_us(seconds: f64) -> u64 {
    if seconds <= 0.0 {
        0
    } else {
        (seconds * 1_000_000.0) as u64
    }
}

fn us_to_secs(us: u64) -> f64 {
    us as f64 / 1_000_000.0
}

// ===========================================================================
// scheduler_api.h C ABI. These are the symbols that satisfy the C++ app's
// references (and thereby keep the C++ TaskManager out of the link).
// ===========================================================================

#[unsafe(no_mangle)]
pub extern "C" fn addRepeatingTask(
    task: TaskHandle,
    priority: u8,
    backOffTime: f64,
    targetTimeBetweenCalls: f64,
    _maxTimeBetweenCalls: f64,
    _name: *const core::ffi::c_char,
    resource: ResourceID,
) -> TaskID {
    // Priority 0 is the audio routine: route it to the preemptive audio
    // interrupt-executor (see AUDIO_EXEC in main) so a thread-mode storage spin
    // can't starve it. All other priorities run cooperatively in thread mode.
    let on_audio = priority == 0;
    claim(
        task,
        None,
        secs_to_us(targetTimeBetweenCalls),
        secs_to_us(backOffTime),
        resource,
        false,
        true,
        on_audio,
    )
}

#[unsafe(no_mangle)]
pub extern "C" fn addOnceTask(
    task: TaskHandle,
    _priority: u8,
    timeToWait: f64,
    _name: *const core::ffi::c_char,
    resource: ResourceID,
) -> TaskID {
    claim(
        task,
        None,
        secs_to_us(timeToWait),
        0,
        resource,
        true,
        true,
        false,
    )
}

#[unsafe(no_mangle)]
pub extern "C" fn addConditionalTask(
    task: TaskHandle,
    _priority: u8,
    condition: RunCondition,
    _name: *const core::ffi::c_char,
    resource: ResourceID,
) -> TaskID {
    claim(task, condition, 0, 0, resource, true, true, false)
}

#[unsafe(no_mangle)]
pub extern "C" fn removeTask(id: TaskID) {
    if let Some(slot) = slot_of(id) {
        slot.stop.store(true, Ordering::Relaxed);
        slot.wake.signal(());
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn blockTask(id: TaskID) {
    if let Some(slot) = slot_of(id) {
        slot.enabled.store(false, Ordering::Relaxed);
        slot.wake.signal(());
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn unblockTask(id: TaskID) {
    if let Some(slot) = slot_of(id) {
        slot.enabled.store(true, Ordering::Relaxed);
        slot.wake.signal(());
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn boostTask(id: TaskID) {
    if let Some(slot) = slot_of(id) {
        slot.boosted.store(true, Ordering::Relaxed);
        slot.wake.signal(());
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn runTask(id: TaskID) {
    // Wake the task so it runs as soon as the executor next polls it.
    if let Some(slot) = slot_of(id) {
        slot.wake.signal(());
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn setNextRunTimeforCurrentTask(seconds: f64) {
    if let Some(slot) = current_slot() {
        slot.next_override_us
            .store(secs_to_us(seconds), Ordering::Relaxed);
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn ignoreForStats() {
    if let Some(slot) = current_slot() {
        slot.count_stats.store(false, Ordering::Relaxed);
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn getAverageRunTimeForTask(id: TaskID) -> f64 {
    slot_of(id).map_or(0.0, |s| us_to_secs(s.avg_run_us.load(Ordering::Relaxed)))
}

#[unsafe(no_mangle)]
pub extern "C" fn getAverageRunTimeforCurrentTask() -> f64 {
    current_slot().map_or(0.0, |s| us_to_secs(s.avg_run_us.load(Ordering::Relaxed)))
}

#[unsafe(no_mangle)]
pub extern "C" fn getSystemTime() -> f64 {
    us_to_secs(Instant::now().as_micros())
}

#[unsafe(no_mangle)]
pub extern "C" fn isSDRoutineActive() -> bool {
    // The app reads this to avoid actions that can't run inside a slow-storage
    // busy-wait. On this BSP there is no such busy-wait: SD goes through the async
    // driver under `block_on` (which parks the executor, so nothing else runs during
    // a transfer anyway) and the legacy `yieldingRoutine*ForSD` hooks aren't linked.
    // So it's always false here.
    false
}

/// On the Embassy BSP the executor *is* the task manager loop, so there is no
/// blocking "start" — tasks are already spawned by `add*Task`. Present only to
/// satisfy the ABI; the bare-metal `deluge_main` path is the one that calls it.
#[unsafe(no_mangle)]
pub extern "C" fn startTaskManager() {}

// ---------------------------------------------------------------------------
// Cooperative yield (scheduler_api.h yield / yieldWithTimeout / yieldToIdle).
//
// The yielding operations (song load, stem export, grid clip create) run on the
// worker fiber (see fiber.rs), so `yield()` suspends the fiber and the executor
// runs everything else until the predicate holds. There is no off-fiber yield on
// this BSP — all yielding ops are dispatched to the worker via deluge_worker_run —
// so the off-fiber path is a defensive no-wait (it never busy-waits and never
// hangs). The legacy `storage_wait.h` hooks (yieldingRoutine*ForSD) are gone here:
// their only callers live in the legacy C HAL (src/RZA1 / src/bsp/rza1), which the
// Embassy BSP does not link — SD goes through the async driver (sd.rs).
// ---------------------------------------------------------------------------

/// Defensive fallback when a `yield*` is somehow reached off the worker fiber
/// (shouldn't happen — every yielding op is dispatched to the worker). Evaluates
/// the predicate once and returns it; never waits, never hangs.
fn off_fiber_yield(until: RunCondition) -> bool {
    // SAFETY: `until` is the C++ caller's predicate; calling it is benign polling.
    until.map_or(true, |p| unsafe { p() })
}

#[unsafe(export_name = "yield")]
pub extern "C" fn r#yield(until: RunCondition) {
    if crate::fiber::on_fiber() {
        crate::fiber::yield_until(until, None);
    } else {
        off_fiber_yield(until);
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn yieldWithTimeout(until: RunCondition, timeout: f64) -> bool {
    if crate::fiber::on_fiber() {
        crate::fiber::yield_until(until, Some(secs_to_us(timeout)))
    } else {
        off_fiber_yield(until)
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn yieldToIdle(until: RunCondition) -> bool {
    if crate::fiber::on_fiber() {
        crate::fiber::yield_until(until, None)
    } else {
        off_fiber_yield(until)
    }
}
