//! block_device.h + FatFS diskio — SD card over `deluge_bsp::sd`, uniformly on
//! both device and host.
//!
//! The app's FatFS layer (its `disk_read`/`disk_write` shims live in
//! audio_file_manager.cpp) calls the BSP-provided `deluge_block_read`/
//! `deluge_block_write` (block_device.h), plus
//! `disk_initialize`/`disk_status`/`disk_ioctl`/`get_fattime`. Both targets back
//! those with `deluge_bsp::sd`'s async `Result<_, SdError>` API
//! (`init`/`read_sectors`/`write_sectors`/`is_ready`/`is_inserted`/
//! `is_write_protected`/`total_sectors`) via `block_on` — no `#[cfg]` needed at
//! the `deluge_bsp::sd` call sites themselves, since deluge-sdk provides `sd`
//! with matching signatures on both targets:
//! - Device: the real SDHI1+DMA driver. SD ops complete on the SDHI/DMA-
//!   completion IRQ. The two device transfer sites (`deluge_block_read`/
//!   `deluge_block_write`) drive the transfer with `block_on_fiber` when
//!   running on the storage-owner fiber (steady state, post-boot) — this
//!   suspends only the fiber and lets the executor (and the app tick →
//!   audio) keep running until the completion IRQ resumes it — or with
//!   `block_on` when not yet on the fiber (only the boot-time FatFS mount,
//!   which runs before the owner exists and has nothing else to run
//!   concurrently with anyway). See the guard at each site and the hazard
//!   note above `deluge_block_read`.
//! - Host (`target_os` != `"none"`): a small file-backed disk image (no SDHI
//!   hardware exists), so the FatFS-shaped C ABI can still be exercised (and
//!   round-tripped) off-target. `deluge_bsp::sd`'s host `init`/`read_sectors`/
//!   `write_sectors` never suspend (there's nothing to await), so `block_on`
//!   is safe here too, and the host sites always use it (no fiber to yield).
//!
//! Per target, the FatFS diskio C-ABI entry points below still need two
//! `#[unsafe(no_mangle)]` definitions (one `#[cfg(target_os = "none")]`, one
//! not) purely because only one symbol of a given name may be linked into a
//! given binary — but each calls the *same* `deluge_bsp::sd` functions, so
//! there is no bespoke per-target storage backend left in this file (that's
//! `deluge_bsp::sd`'s job). No C++ app is currently linked on host, so the
//! FatFS `disk_*` entry points are otherwise unused there; they're still given
//! working host bodies (rather than gated out) since a future host FatFS
//! exercise will call them.
//!
//! This file also hosts `deluge_storage_on_owner`, a query the Embassy diskio
//! shims use to assert single-owner access; it just forwards to
//! `crate::fiber::on_fiber()`.
#![allow(non_upper_case_globals)]

use core::sync::atomic::{AtomicBool, Ordering};

use deluge_bsp::sd;
use embassy_futures::block_on;

#[cfg(target_os = "none")]
use crate::fiber::block_on_fiber;
#[cfg(all(not(target_os = "none"), feature = "sim_latency"))]
use crate::fiber::block_on_fiber;

#[cfg(target_os = "none")]
use crate::sys::{
    DelugeCardEvent, DelugeCardEvent_DELUGE_CARD_EVENT_EJECTED as CARD_EJECTED,
    DelugeCardEvent_DELUGE_CARD_EVENT_INSERTED as CARD_INSERTED,
    DelugeCardEvent_DELUGE_CARD_EVENT_NONE as CARD_NONE, DelugeStatus,
    DelugeStatus_DELUGE_ERR_IO as DELUGE_ERR_IO, DelugeStatus_DELUGE_ERR_NODEV as DELUGE_ERR_NODEV,
    DelugeStatus_DELUGE_ERR_WRITE_PROTECTED as DELUGE_ERR_WRITE_PROTECTED,
    DelugeStatus_DELUGE_OK as DELUGE_OK,
};

// Host stand-ins for the bindgen `crate::sys` types used below (`block_device.h`
// / `types.h`). This is UNRELATED to `deluge_bsp::sd` now being dual-target —
// `mod sys` is generated by *this crate's* build.rs from the C++ app's headers,
// and build.rs skips bindgen entirely on host (no C++ app is linked there; see
// its top-of-file comment), so `crate::sys` simply doesn't exist to import on
// host, independent of what deluge-sdk exposes. Mirror the C types' shapes
// directly here instead (same convention as fiber.rs's `RunCondition`):
// `DelugeStatus` is `i8` (its values run -13..=0, the width clang's
// `-fshort-enums` would pick for the armv7a app), `DelugeCardEvent` is `u8`
// (0..=2). Values match include/libdeluge/{types,block_device}.h exactly, so
// the full card-event edge-tracking algorithm in
// `deluge_block_poll_card_event` below runs identically on both targets.
#[cfg(not(target_os = "none"))]
type DelugeStatus = i8;
#[cfg(not(target_os = "none"))]
const DELUGE_OK: DelugeStatus = 0;
#[cfg(not(target_os = "none"))]
const DELUGE_ERR_IO: DelugeStatus = -5;
#[cfg(not(target_os = "none"))]
const DELUGE_ERR_NODEV: DelugeStatus = -6;
#[cfg(not(target_os = "none"))]
const DELUGE_ERR_WRITE_PROTECTED: DelugeStatus = -12;

#[cfg(not(target_os = "none"))]
type DelugeCardEvent = u8;
#[cfg(not(target_os = "none"))]
const CARD_NONE: DelugeCardEvent = 0;
#[cfg(not(target_os = "none"))]
const CARD_INSERTED: DelugeCardEvent = 1;
#[cfg(not(target_os = "none"))]
const CARD_EJECTED: DelugeCardEvent = 2;

// FatFS diskio status/result codes (src/fatfs/diskio.h).
const STA_NOINIT: u8 = 0x01;
const STA_NODISK: u8 = 0x02;
const STA_PROTECT: u8 = 0x04;
const RES_OK: i32 = 0;
const RES_ERROR: i32 = 1;
const RES_WRPRT: i32 = 2;
const RES_NOTRDY: i32 = 3;
const RES_PARERR: i32 = 4;
const CTRL_SYNC: u8 = 0;
const GET_SECTOR_COUNT: u8 = 1;
const GET_SECTOR_SIZE: u8 = 2;
const GET_BLOCK_SIZE: u8 = 3;
const SECTOR_SIZE: usize = 512;

/// Set once `disk_initialize` has driven `sd::init()` at least once. Until then,
/// the controller has never muxed `SD_CD` (P7_0 → SDHI fn 3) or started `SD_CLK`,
/// so `sd::is_inserted()` reads a meaningless card-detect line. We must NOT report
/// `STA_NODISK` from that pre-init read: FatFS skips `disk_initialize` whenever the
/// disk looks absent, and `disk_initialize` is the only path that brings the detect
/// circuit to life — detection would be gated on init, and init on detection
/// (deadlock). Report "not initialized, presence unknown" instead so FatFS attempts
/// the init that makes card-detect valid. Device-only: `deluge_bsp::sd`'s host
/// stand-in has no controller bring-up step.
#[cfg(target_os = "none")]
static CONTROLLER_UP: AtomicBool = AtomicBool::new(false);

/// Bring the SD controller up from an async (Embassy task) context, once at boot.
///
/// `sd::init()` sequences card power-up with `embassy_time::Timer` delays. This BSP
/// uses the *integrated* (intrusive) timer queue, so a `Timer` only resolves when
/// polled by a real Embassy task — `embassy_futures::block_on`'s synthetic waker
/// makes `Timer` panic (`from_embassy_waker`). The sync FatFS `disk_initialize`
/// path can therefore never run `init()`. Instead we init here, from `app_task`,
/// before `deluge_app_init` drives the first C++ storage access: afterwards the card
/// reports ready, FatFS skips `disk_initialize`, and reads/writes stay on `block_on`
/// (pure SDHI/DMA-IRQ futures — no timers). Re-runnable for card-swap from async.
/// Device-only: `app_task` (this fn's sole caller) is itself device-only.
#[cfg(target_os = "none")]
pub async fn boot_init() {
    let r = sd::init().await;
    // The pin mux + SDHI bring-up has run, so card-detect is meaningful now.
    CONTROLLER_UP.store(true, Ordering::Release);
    log::info!(
        "sd: boot_init — init={:?} inserted={} wp={}",
        r.is_ok(),
        sd::is_inserted(),
        sd::is_write_protected(),
    );
}

/// `host_app` sibling of the device [`boot_init`] above: called from the host
/// `app_task` (`main.rs`) before `deluge_app_init`, purely to mirror the device
/// boot sequencing exactly. Not strictly required on host — unlike the device
/// (whose integrated timer queue makes `sd::init()`'s `Timer` delays unusable
/// under `disk_initialize`'s synchronous `block_on`, see the host
/// `disk_initialize` doc comment below), `deluge_bsp::sd`'s host `init()` never
/// suspends, so `disk_initialize` already drives it lazily via `block_on` on
/// first FatFS access with no separate async bring-up step needed. Calling it
/// here too is harmless (idempotent) and keeps the host and device `app_task`
/// bodies textually identical.
#[cfg(all(not(target_os = "none"), feature = "host_app"))]
pub async fn boot_init() {
    let r = sd::init().await;
    log::info!(
        "sd: boot_init (host) — init={:?} inserted={} wp={}",
        r.is_ok(),
        sd::is_inserted(),
        sd::is_write_protected(),
    );
}

/// Thin async wrapper around `deluge_bsp::sd::read_sectors` for the R1 streaming
/// fill task (`streaming_loader.rs`). Same dual-target shape as the rest of this
/// file — no `#[cfg]` needed at the call site. R3: wrap in SD_BUS mutex (the real
/// cross-owner exclusion against the recorder / other SD callers lands there);
/// for now this just forwards.
pub async fn locked_read_sectors(lba: u32, count: u32, buf: &mut [u8]) -> Result<(), sd::SdError> {
    sd::read_sectors(lba, count, buf).await
}

/// FatFS DSTATUS bits for the current card state. Device-only (see [`sd`]).
#[cfg(target_os = "none")]
fn status_bits() -> u8 {
    // DIAG (SD bring-up): log the raw card-detect/ready state the first few times
    // status is queried, so "No SD card present" can be traced to is_inserted()
    // vs. is_ready() vs. init failure.
    {
        static DIAG_LEFT: AtomicBool = AtomicBool::new(true);
        if DIAG_LEFT.swap(false, Ordering::Relaxed) {
            log::info!(
                "DIAG sd: status_bits — inserted={} ready={} wp={}",
                sd::is_inserted(),
                sd::is_ready(),
                sd::is_write_protected(),
            );
        }
    }
    if !sd::is_ready() {
        // Only trust the card-detect read once the controller has been brought up.
        let absent = CONTROLLER_UP.load(Ordering::Acquire) && !sd::is_inserted();
        return STA_NOINIT | if absent { STA_NODISK } else { 0 };
    }
    if sd::is_write_protected() {
        STA_PROTECT
    } else {
        0
    }
}

#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn disk_initialize(pdrv: u8) -> u8 {
    if pdrv != 0 {
        return STA_NOINIT;
    }
    // sd::init() can't run here: its embassy-time Timers panic under `block_on`
    // (integrated timer queue — see `boot_init`). It runs eagerly from `app_task`
    // (boot_init) after the PIC baud handshake (pic::wait_ready) and before
    // deluge_app_init — waiting for the PIC first avoids the handshake race that
    // corrupted the pads. So the card is ready by the time the app first calls this;
    // if somehow not, just report status (never block_on(init) here).
    if !sd::is_ready() {
        log::warn!("sd: disk_initialize before async init done");
    }
    status_bits()
}

#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn disk_status(pdrv: u8) -> u8 {
    if pdrv != 0 {
        return STA_NOINIT;
    }
    status_bits()
}

/// Host: no controller bring-up or card-detect exists — `deluge_bsp::sd`'s
/// file-backed disk image is ready as soon as it can be opened/sized.
/// `sd::init()` never suspends on host (there's no hardware to await), so
/// unlike the device path (see [`boot_init`]) it's safe to drive to completion
/// with `block_on` right here rather than needing a separate async bring-up
/// step. Both FatFS DSTATUS entry points then just report "ready" for unit 0.
#[cfg(not(target_os = "none"))]
#[unsafe(no_mangle)]
pub extern "C" fn disk_initialize(pdrv: u8) -> u8 {
    if pdrv != 0 {
        return STA_NOINIT;
    }
    let _ = block_on(sd::init());
    0
}

#[cfg(not(target_os = "none"))]
#[unsafe(no_mangle)]
pub extern "C" fn disk_status(pdrv: u8) -> u8 {
    if pdrv != 0 {
        return STA_NOINIT;
    }
    0
}

#[unsafe(no_mangle)]
pub extern "C" fn disk_ioctl(pdrv: u8, cmd: u8, buff: *mut core::ffi::c_void) -> i32 {
    if pdrv != 0 {
        return RES_NOTRDY;
    }
    match cmd {
        // Writes complete synchronously (block_on / a direct host file write), so
        // nothing is ever pending.
        CTRL_SYNC => RES_OK,
        GET_SECTOR_COUNT => {
            if buff.is_null() {
                return RES_PARERR;
            }
            // No `#[cfg]` needed here: `sd::total_sectors()` resolves to the
            // device SDHI driver or the host file-backed image internally.
            let sectors = sd::total_sectors();
            unsafe { *(buff as *mut u32) = sectors };
            RES_OK
        }
        GET_SECTOR_SIZE => {
            if buff.is_null() {
                return RES_PARERR;
            }
            unsafe { *(buff as *mut u16) = SECTOR_SIZE as u16 };
            RES_OK
        }
        GET_BLOCK_SIZE => {
            if buff.is_null() {
                return RES_PARERR;
            }
            unsafe { *(buff as *mut u32) = 1 };
            RES_OK
        }
        _ => RES_PARERR,
    }
}

/// libdeluge/storage_owner.h — Embassy: the storage owner IS the worker fiber.
#[unsafe(no_mangle)]
pub extern "C" fn deluge_storage_on_owner() -> bool {
    crate::fiber::on_fiber()
}

// HISTORY: a prior attempt drove SD I/O with a fiber-yielding
// `block_on_fiber` unconditionally. FatFS is not re-entrant, and the app's
// SD-reentrancy guard (`currentlyAccessingCard`) is only set by the legacy C
// diskio (src/RZA1/diskio.c), which this BSP does not link — so on this BSP
// it is always 0. Yielding mid-transfer let other tasks re-enter FatFS
// concurrently and corrupted it (manifested as "NO MORE PRESETS FOUND" on
// track create, and would also break song/sample loads).
//
// That precondition — serialize all SD access first — is now MET: the
// async-sd staging ladder (single-owner routing enforced by
// `deluge_storage_on_owner`/`storage-owner-audit`, plus the priority-queue
// and cooperative-yield rungs) guarantees every FatFS transfer after the
// storage owner is up runs on the single worker fiber, one at a time. The
// device transfer sites below now flip on that guarantee: `if on_fiber() {
// block_on_fiber(fut) } else { block_on(fut) }`. The `on_fiber()` branch
// (steady state, post-boot) yields the fiber mid-transfer so the executor
// can run other work while the SDHI/DMA completion IRQ is pending — no
// re-entrancy, because FatFS calls only ever originate from the one owner
// fiber, which stays suspended (not re-entered) until its own transfer
// completes. The `else` branch (only the boot-time FatFS mount, which runs
// before the worker/owner exists) still parks via `block_on`, since nothing
// else can run concurrently at that point anyway.
#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_read(
    unit: u8,
    dst: *mut u8,
    sector: u32,
    count: u32,
) -> DelugeStatus {
    // Gated on `worker_started()`, not `on_fiber()` alone: the boot-time FatFS
    // mount (`StorageManager::initSD()` -> `f_mount` -> this fn) runs
    // synchronously in `deluge_boot()` BEFORE the worker/owner exists — no
    // fiber to be on yet. That's expected and safe in isolation: the rung-5
    // flip's guard is `if on_fiber() { block_on_fiber } else { block_on }`, so
    // the boot mount takes the parking `block_on` branch, which cannot corrupt
    // FatFS since nothing else can run concurrently before the owner is up.
    // Once the owner IS up (`worker_started()`), every transfer must be on the
    // fiber — this audits that.
    #[cfg(feature = "storage-owner-audit")]
    debug_assert!(
        crate::fiber::on_fiber() || !crate::fiber::worker_started(),
        "FatFS card transfer off the storage owner after the owner started — \
         single-owner discipline violated at runtime (async-sd staging ladder)"
    );
    if unit != 0 || !sd::is_ready() {
        return DELUGE_ERR_NODEV;
    }
    let len = count as usize * SECTOR_SIZE;
    // SAFETY: caller guarantees `dst` holds `count` sectors.
    let out = unsafe { core::slice::from_raw_parts_mut(dst, len) };
    let fut = sd::read_sectors(sector, count, out);
    match if crate::fiber::on_fiber() {
        block_on_fiber(fut)
    } else {
        block_on(fut)
    } {
        Ok(()) => DELUGE_OK,
        Err(_) => DELUGE_ERR_IO,
    }
}

#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_write(
    unit: u8,
    src: *const u8,
    sector: u32,
    count: u32,
) -> DelugeStatus {
    // Gated on `worker_started()`, not `on_fiber()` alone: the boot-time FatFS
    // mount (`StorageManager::initSD()` -> `f_mount` -> this fn) runs
    // synchronously in `deluge_boot()` BEFORE the worker/owner exists — no
    // fiber to be on yet. That's expected and safe in isolation: the rung-5
    // flip's guard is `if on_fiber() { block_on_fiber } else { block_on }`, so
    // the boot mount takes the parking `block_on` branch, which cannot corrupt
    // FatFS since nothing else can run concurrently before the owner is up.
    // Once the owner IS up (`worker_started()`), every transfer must be on the
    // fiber — this audits that.
    #[cfg(feature = "storage-owner-audit")]
    debug_assert!(
        crate::fiber::on_fiber() || !crate::fiber::worker_started(),
        "FatFS card transfer off the storage owner after the owner started — \
         single-owner discipline violated at runtime (async-sd staging ladder)"
    );
    if unit != 0 || !sd::is_ready() {
        return DELUGE_ERR_NODEV;
    }
    if sd::is_write_protected() {
        return DELUGE_ERR_WRITE_PROTECTED;
    }
    let len = count as usize * SECTOR_SIZE;
    // SAFETY: caller guarantees `src` holds `count` sectors.
    let data = unsafe { core::slice::from_raw_parts(src, len) };
    let fut = sd::write_sectors(sector, count, data);
    match if crate::fiber::on_fiber() {
        block_on_fiber(fut)
    } else {
        block_on(fut)
    } {
        Ok(()) => DELUGE_OK,
        Err(e) => {
            log::warn!("deluge_block_write err {e:?} (sector={sector} count={count})");
            DELUGE_ERR_IO
        }
    }
}

/// Host-only instrumentation (streaming-underrun harness): counts SD block reads/writes
/// that happen ON THE STORAGE-OWNER FIBER (`fiber::on_fiber()` true at the call site) —
/// i.e. transfers that genuinely reached the fiber+priority dispatch machinery, as
/// opposed to the boot-time FatFS mount or any other off-fiber access (which always
/// runs `block_on`-only and never suspends). This is the evidence the streaming-underrun
/// harness's scenario driver (`scenario.rs`) asserts on: a real queued cluster read
/// (`loader::request_pump`, HIGH priority) or recorder card-write
/// (`requestRecorderCardRoutines`, SD-routine) actually DRAINED through
/// `fiber::worker_poll()`, not just that the dispatch was attempted. Compiled for every
/// host build (not gated on `host_app`/`sim_latency`) — the counters sit idle (never
/// read) unless something calls the `on_fiber_*` getters below.
#[cfg(not(target_os = "none"))]
pub(crate) mod stats {
    use core::sync::atomic::{AtomicU64, Ordering};

    static ON_FIBER_READS: AtomicU64 = AtomicU64::new(0);
    static ON_FIBER_WRITES: AtomicU64 = AtomicU64::new(0);

    pub(crate) fn note_read(on_fiber: bool) {
        if on_fiber {
            ON_FIBER_READS.fetch_add(1, Ordering::Relaxed);
        }
    }

    pub(crate) fn note_write(on_fiber: bool) {
        if on_fiber {
            ON_FIBER_WRITES.fetch_add(1, Ordering::Relaxed);
        }
    }

    /// Total SD block reads observed while `fiber::on_fiber()` was true (any host
    /// `deluge_block_read` variant — plain or `sim_latency`).
    pub fn on_fiber_reads() -> u64 {
        ON_FIBER_READS.load(Ordering::Relaxed)
    }

    /// Total SD block writes observed while `fiber::on_fiber()` was true (any host
    /// `deluge_block_write` variant — plain or `sim_latency`).
    pub fn on_fiber_writes() -> u64 {
        ON_FIBER_WRITES.load(Ordering::Relaxed)
    }
}

/// Host: read `count` sectors via `deluge_bsp::sd::read_sectors` — the SAME
/// call the device path (above) makes, now backed by `deluge_bsp::sd`'s
/// file-backed disk image instead of a local shim. No card-detect concept on
/// host — `DELUGE_ERR_NODEV` is only for a non-zero unit. Deliberately does
/// NOT gate on `sd::is_ready()` (unlike the device path): the host image is
/// usable as soon as `deluge_bsp::sd` lazily opens/sizes its backing file on
/// first access, with no async bring-up step required first, and the host
/// harness's round-trip check (see `main.rs`) exercises this ABI directly
/// without calling `disk_initialize`/`sd::init()` beforehand.
///
/// `sim_latency`-off only: with that feature on, [`sim_latency`]'s sibling
/// below (same signature) takes over — see its doc comment.
#[cfg(all(not(target_os = "none"), not(feature = "sim_latency")))]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_read(
    unit: u8,
    dst: *mut u8,
    sector: u32,
    count: u32,
) -> DelugeStatus {
    // Gated on `worker_started()`, not `on_fiber()` alone: the boot-time FatFS
    // mount (`StorageManager::initSD()` -> `f_mount` -> this fn) runs
    // synchronously in `deluge_boot()` BEFORE the worker/owner exists — no
    // fiber to be on yet. That's expected and safe in isolation: the rung-5
    // flip's guard is `if on_fiber() { block_on_fiber } else { block_on }`, so
    // the boot mount takes the parking `block_on` branch, which cannot corrupt
    // FatFS since nothing else can run concurrently before the owner is up.
    // Once the owner IS up (`worker_started()`), every transfer must be on the
    // fiber — this audits that.
    #[cfg(feature = "storage-owner-audit")]
    debug_assert!(
        crate::fiber::on_fiber() || !crate::fiber::worker_started(),
        "FatFS card transfer off the storage owner after the owner started — \
         single-owner discipline violated at runtime (async-sd staging ladder)"
    );
    if unit != 0 {
        return DELUGE_ERR_NODEV;
    }
    stats::note_read(crate::fiber::on_fiber());
    let len = count as usize * SECTOR_SIZE;
    // SAFETY: caller guarantees `dst` holds `count` sectors.
    let out = unsafe { core::slice::from_raw_parts_mut(dst, len) };
    match block_on(sd::read_sectors(sector, count, out)) {
        Ok(()) => DELUGE_OK,
        Err(e) => {
            log::warn!("deluge_block_read(host) err {e:?} (sector={sector} count={count})");
            DELUGE_ERR_IO
        }
    }
}

/// Host: write `count` sectors via `deluge_bsp::sd::write_sectors` (see
/// [`deluge_block_read`] above for why there's no `is_ready()` gate here).
/// `sd::is_write_protected()` is still checked — it always reads `false` on
/// host (a plain file has no write-protect concept), so this is a no-op today,
/// but it keeps the call site identical to the device path.
///
/// `sim_latency`-off only: with that feature on, [`sim_latency`]'s sibling
/// below (same signature) takes over — see its doc comment.
#[cfg(all(not(target_os = "none"), not(feature = "sim_latency")))]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_write(
    unit: u8,
    src: *const u8,
    sector: u32,
    count: u32,
) -> DelugeStatus {
    // Gated on `worker_started()`, not `on_fiber()` alone: the boot-time FatFS
    // mount (`StorageManager::initSD()` -> `f_mount` -> this fn) runs
    // synchronously in `deluge_boot()` BEFORE the worker/owner exists — no
    // fiber to be on yet. That's expected and safe in isolation: the rung-5
    // flip's guard is `if on_fiber() { block_on_fiber } else { block_on }`, so
    // the boot mount takes the parking `block_on` branch, which cannot corrupt
    // FatFS since nothing else can run concurrently before the owner is up.
    // Once the owner IS up (`worker_started()`), every transfer must be on the
    // fiber — this audits that.
    #[cfg(feature = "storage-owner-audit")]
    debug_assert!(
        crate::fiber::on_fiber() || !crate::fiber::worker_started(),
        "FatFS card transfer off the storage owner after the owner started — \
         single-owner discipline violated at runtime (async-sd staging ladder)"
    );
    if unit != 0 {
        return DELUGE_ERR_NODEV;
    }
    if sd::is_write_protected() {
        return DELUGE_ERR_WRITE_PROTECTED;
    }
    stats::note_write(crate::fiber::on_fiber());
    let len = count as usize * SECTOR_SIZE;
    // SAFETY: caller guarantees `src` holds `count` sectors.
    let data = unsafe { core::slice::from_raw_parts(src, len) };
    match block_on(sd::write_sectors(sector, count, data)) {
        Ok(()) => DELUGE_OK,
        Err(e) => {
            log::warn!("deluge_block_write(host) err {e:?} (sector={sector} count={count})");
            DELUGE_ERR_IO
        }
    }
}

/// Host, `sim_latency` feature: same file-backed data path as the plain host
/// `deluge_block_read` above, but the transfer future is wrapped by
/// [`sim_latency::modeled_read`], which pends on a MODELED per-transfer
/// latency ([`sim_latency::latency_for`]) before completing with the real
/// file-image data — and, critically, is driven through the SAME
/// `on_fiber()`-guarded `block_on_fiber`/`block_on` shape the device transfer
/// sites (above) already use, instead of the plain host path's `block_on`-
/// only (never-suspends) shape. A read issued on the storage-owner fiber
/// therefore genuinely SUSPENDS the fiber (yielding to the executor, which
/// keeps running every other task) for the modeled delay, letting a harness
/// measure the fill-vs-drain race — see `sim_latency`'s module doc.
///
/// Mutually exclusive with the plain host `deluge_block_read` above (disjoint
/// `#[cfg]`s): with `sim_latency` off, this function does not exist and the
/// plain sibling compiles unchanged, so normal host/device/golden builds are
/// byte-identical to before this feature existed.
#[cfg(all(not(target_os = "none"), feature = "sim_latency"))]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_read(
    unit: u8,
    dst: *mut u8,
    sector: u32,
    count: u32,
) -> DelugeStatus {
    // See the plain host `deluge_block_read`'s identical comment above for the
    // `worker_started()` vs. `on_fiber()` rationale.
    #[cfg(feature = "storage-owner-audit")]
    debug_assert!(
        crate::fiber::on_fiber() || !crate::fiber::worker_started(),
        "FatFS card transfer off the storage owner after the owner started — \
         single-owner discipline violated at runtime (async-sd staging ladder)"
    );
    if unit != 0 {
        return DELUGE_ERR_NODEV;
    }
    let on_fiber = crate::fiber::on_fiber();
    stats::note_read(on_fiber);
    let len = count as usize * SECTOR_SIZE;
    // SAFETY: caller guarantees `dst` holds `count` sectors.
    let out = unsafe { core::slice::from_raw_parts_mut(dst, len) };
    let result = if on_fiber {
        block_on_fiber(sim_latency::modeled_read(sector, count, out))
    } else if sim_latency::off_fiber_instant() {
        // See `sim_latency::off_fiber_instant`'s doc comment.
        block_on(sd::read_sectors(sector, count, out))
    } else {
        block_on(sim_latency::modeled_read(sector, count, out))
    };
    match result {
        Ok(()) => DELUGE_OK,
        Err(e) => {
            log::warn!(
                "deluge_block_read(host, sim_latency) err {e:?} (sector={sector} count={count})"
            );
            DELUGE_ERR_IO
        }
    }
}

/// Host, `sim_latency` feature: write sibling of [`deluge_block_read`]
/// (above) — see its doc comment for the full rationale.
#[cfg(all(not(target_os = "none"), feature = "sim_latency"))]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_write(
    unit: u8,
    src: *const u8,
    sector: u32,
    count: u32,
) -> DelugeStatus {
    #[cfg(feature = "storage-owner-audit")]
    debug_assert!(
        crate::fiber::on_fiber() || !crate::fiber::worker_started(),
        "FatFS card transfer off the storage owner after the owner started — \
         single-owner discipline violated at runtime (async-sd staging ladder)"
    );
    if unit != 0 {
        return DELUGE_ERR_NODEV;
    }
    if sd::is_write_protected() {
        return DELUGE_ERR_WRITE_PROTECTED;
    }
    let on_fiber = crate::fiber::on_fiber();
    stats::note_write(on_fiber);
    let len = count as usize * SECTOR_SIZE;
    // SAFETY: caller guarantees `src` holds `count` sectors.
    let data = unsafe { core::slice::from_raw_parts(src, len) };
    let result = if on_fiber {
        block_on_fiber(sim_latency::modeled_write(sector, count, data))
    } else if sim_latency::off_fiber_instant() {
        // See `sim_latency::off_fiber_instant`'s doc comment.
        block_on(sd::write_sectors(sector, count, data))
    } else {
        block_on(sim_latency::modeled_write(sector, count, data))
    };
    match result {
        Ok(()) => DELUGE_OK,
        Err(e) => {
            log::warn!(
                "deluge_block_write(host, sim_latency) err {e:?} (sector={sector} count={count})"
            );
            DELUGE_ERR_IO
        }
    }
}

/// Sim-only (harness) modeled-latency substrate for host SD transfers. Gated
/// entirely behind the `sim_latency` cargo feature (OFF by default — see
/// `Cargo.toml`'s doc comment), so a normal host/device/golden build never
/// compiles any of this in.
///
/// ## Why the modeled delay can't just be `Timer::after(...).await`ed inline
///
/// The obvious shape — have `deluge_block_read`'s future do
/// `Timer::after(latency_for(bytes)).await` directly, then call
/// `sd::read_sectors` — does NOT work when that future is driven by
/// [`crate::fiber::block_on_fiber`] (the on-fiber branch) or
/// `embassy_futures::block_on` (the off-fiber branch): both poll the future
/// with a synthetic `Waker` that is not a genuine embassy-executor TASK waker,
/// and `embassy-time`'s integrated timer queue (this workspace pins the
/// `timer-item-size-*`/integrated variant — see `Cargo.toml`'s patch section)
/// panics on exactly that (`TimerQueueItem::from_embassy_waker`: "Panics if
/// called with a non-embassy waker"). This is the same constraint already
/// documented at this file's `boot_init` (`sd::init()`'s Timers can't run
/// under `block_on`).
///
/// So the actual `Timer::after` await happens in [`pump`], a genuine spawned
/// Embassy task (a real per-task waker — whichever executor/harness spawns
/// it, on the virtual `MockDriver` clock or the host `std` clock, per
/// `embassy-time`'s linked driver; this module never touches a clock
/// directly). [`delay`] hands `pump` a duration over a `Signal` and awaits
/// completion via a plain [`embassy_sync::waitqueue::AtomicWaker`] — safe to
/// poll from ANY waker, including `block_on_fiber`'s/`block_on`'s synthetic
/// ones — so the read/write call sites above can stay on the same
/// `on_fiber()`-guarded shape the device path already uses.
///
/// SD transfers are already single-owner-serialized (this file's module doc
/// + `deluge_storage_on_owner`), so at most one modeled transfer is ever in
/// flight — a single request/completion slot suffices; no per-transfer task
/// spawning or queueing is needed.
#[cfg(all(not(target_os = "none"), feature = "sim_latency"))]
pub mod sim_latency {
    use core::future::Future;
    use core::pin::Pin;
    use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};
    use core::task::{Context, Poll};

    use deluge_bsp::sd;
    use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
    use embassy_sync::signal::Signal;
    use embassy_sync::waitqueue::AtomicWaker;
    use embassy_time::{Duration, Timer};

    use super::SECTOR_SIZE;

    /// Modeled throughput, bytes/sec — the `bytes / throughput` term of the
    /// latency model. Overridable at runtime (a plain `Relaxed` static, not a
    /// `const`) so a harness sweep can vary it per run without a rebuild.
    /// Default: a plausible sustained SD sequential-transfer rate.
    static THROUGHPUT_BYTES_PER_SEC: AtomicU32 = AtomicU32::new(20_000_000);
    /// Modeled fixed per-command overhead, microseconds — the command/
    /// response round-trip latency independent of transfer size. Overridable
    /// for the same reason as [`THROUGHPUT_BYTES_PER_SEC`].
    static COMMAND_OVERHEAD_US: AtomicU32 = AtomicU32::new(500);

    /// Override the modeled throughput (bytes/sec; clamped to at least 1 so
    /// [`latency_for`] never divides by zero).
    pub fn set_throughput_bytes_per_sec(bytes_per_sec: u32) {
        THROUGHPUT_BYTES_PER_SEC.store(bytes_per_sec.max(1), Ordering::Relaxed);
    }

    /// Override the modeled fixed command overhead (microseconds).
    pub fn set_command_overhead_us(us: u32) {
        COMMAND_OVERHEAD_US.store(us, Ordering::Relaxed);
    }

    /// Escape hatch for single-threaded deterministic-clock harnesses: when true,
    /// a modeled read/write issued OFF the storage-owner fiber
    /// (`deluge_block_read`/`_write`'s `on_fiber` branch above) skips
    /// [`delay`]/[`pump`] entirely and goes straight to the real transfer. Off
    /// (`false`) by default, preserving today's behavior for every existing
    /// consumer — manual `cargo run --features host_app,sim_latency` testing, and
    /// any multi-threaded harness, which can instead resolve the same off-fiber
    /// livelock by running [`pump`] on a separate OS thread.
    ///
    /// A single-threaded executor has no second thread available for that
    /// thread-based fix, and needs this flag instead: `deluge_app_init` calls the
    /// boot-time FatFS mount SYNCHRONOUSLY, and `embassy_futures::block_on`'s
    /// tight poll loop never yields back to the executor, so `pump`'s `Timer`
    /// could never be polled — the mount would livelock waiting on a delay
    /// nothing can ever complete. The only off-fiber `sim_latency` transfers on
    /// such a harness are that boot-time mount (before the worker/owner exists,
    /// so nothing else could usefully run concurrently with it anyway — see
    /// `deluge_block_read`'s own `worker_started()` doc comment) plus a handful
    /// of essential-sample reads `deluge_app_init` may issue synchronously during
    /// the same call — none of which have a real-time deadline the underrun
    /// counters care about (matches `ScenarioConfig::post_load_sim_latency`'s
    /// existing "load's own reads don't need modeling" rationale). Set this once
    /// at startup, before any transfer; ON-fiber reads (the actual streaming
    /// path, post-boot) are UNAFFECTED and keep modeling latency normally —
    /// those suspend via [`crate::fiber::block_on_fiber`]'s genuine coroutine
    /// yield, which the normal quiescence-loop-driven executor handles without
    /// any special-casing.
    static OFF_FIBER_INSTANT: AtomicBool = AtomicBool::new(false);

    /// See [`OFF_FIBER_INSTANT`]'s doc comment.
    pub fn set_off_fiber_instant(instant: bool) {
        OFF_FIBER_INSTANT.store(instant, Ordering::Relaxed);
    }

    pub(super) fn off_fiber_instant() -> bool {
        OFF_FIBER_INSTANT.load(Ordering::Relaxed)
    }

    /// Modeled latency for a `bytes`-byte transfer: fixed command overhead
    /// plus `bytes / throughput`. A simple throughput + fixed-overhead model
    /// (not a hardware-accurate SD timing simulation) — sufficient for a
    /// harness to observe a fill-vs-drain race, and cheap to reason about.
    pub fn latency_for(bytes: usize) -> Duration {
        let throughput_bps = THROUGHPUT_BYTES_PER_SEC.load(Ordering::Relaxed) as u64;
        let overhead_us = COMMAND_OVERHEAD_US.load(Ordering::Relaxed) as u64;
        let transfer_us = (bytes as u64 * 1_000_000) / throughput_bps;
        Duration::from_micros(overhead_us + transfer_us)
    }

    /// Single-flight request handoff to [`pump`]: the duration for the
    /// in-flight modeled transfer. A single slot suffices — see the module
    /// doc's single-owner-serialization note.
    static REQUEST: Signal<CriticalSectionRawMutex, Duration> = Signal::new();
    /// Set by [`pump`] once its `Timer` for the current request has elapsed;
    /// cleared by [`DelayFuture`]'s poll on consumption.
    static DONE: AtomicBool = AtomicBool::new(false);
    /// Woken by [`pump`] on completion; registered by [`DelayFuture`]'s poll.
    /// A plain waitqueue primitive — safe to be woken from, or register a
    /// waker from, any thread/context, unlike `embassy-time`'s Timer (see the
    /// module doc).
    static WAKER: AtomicWaker = AtomicWaker::new();

    /// Background task: the ONLY place in this module that actually awaits
    /// `embassy_time::Timer` — see the module doc for why. Must be spawned
    /// once onto whichever Embassy executor the harness brings up (e.g.
    /// alongside `fiber`'s `worker_pump` task) before any `sim_latency`
    /// transfer is issued; loops forever, one modeled delay at a time.
    #[embassy_executor::task]
    pub async fn pump() {
        loop {
            let dur = REQUEST.wait().await;
            Timer::after(dur).await;
            DONE.store(true, Ordering::SeqCst);
            WAKER.wake();
        }
    }

    /// A completion future safe to poll from any `Waker` — including
    /// [`crate::fiber::block_on_fiber`]'s and `embassy_futures::block_on`'s
    /// synthetic ones (see the module doc). Registers with [`WAKER`] before
    /// checking [`DONE`] (register-then-check ordering avoids a lost wake if
    /// [`pump`] completes between the check and the registration).
    struct DelayFuture;
    impl Future for DelayFuture {
        type Output = ();
        fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
            WAKER.register(cx.waker());
            if DONE.swap(false, Ordering::SeqCst) {
                Poll::Ready(())
            } else {
                Poll::Pending
            }
        }
    }

    /// Await the modeled latency for a `bytes`-byte transfer, driven by
    /// [`pump`].
    async fn delay(bytes: usize) {
        REQUEST.signal(latency_for(bytes));
        DelayFuture.await;
    }

    /// The modeled-latency wrapper future for a host read: pends on the
    /// modeled per-transfer delay, then performs the real (synchronous,
    /// file-backed) read. Only the timing is modeled; the data comes from
    /// the same `deluge_bsp::sd::read_sectors` the plain host path uses.
    pub async fn modeled_read(lba: u32, count: u32, buf: &mut [u8]) -> Result<(), sd::SdError> {
        delay(count as usize * SECTOR_SIZE).await;
        sd::read_sectors(lba, count, buf).await
    }

    /// Write sibling of [`modeled_read`].
    pub async fn modeled_write(lba: u32, count: u32, buf: &[u8]) -> Result<(), sd::SdError> {
        delay(count as usize * SECTOR_SIZE).await;
        sd::write_sectors(lba, count, buf).await
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn disk_timerproc() {
    // SD is fully event-driven (SDHI/DMA IRQs); no periodic timer work needed.
}

#[unsafe(no_mangle)]
pub extern "C" fn get_fattime() -> u32 {
    // 2024-01-01 00:00:00, FAT-packed. No RTC on this BSP yet.
    ((2024u32 - 1980) << 25) | (1 << 21) | (1 << 16)
}

// ── block_device.h: SD unit + card-detect ─────────────────────────────────────

#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_sd_unit() -> u8 {
    0
}

/// Pull-based card-detect: report INSERTED/EJECTED edges of the card-present
/// state. The first poll just latches the boot state (no spurious event), so the
/// app's initial card read isn't double-triggered (mirrors the rza1 latch).
#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_poll_card_event(unit: u8) -> DelugeCardEvent {
    if unit != 0 {
        return CARD_NONE;
    }
    static INITIALISED: AtomicBool = AtomicBool::new(false);
    static LAST_INSERTED: AtomicBool = AtomicBool::new(false);
    let now = sd::is_inserted();
    if !INITIALISED.swap(true, Ordering::Relaxed) {
        LAST_INSERTED.store(now, Ordering::Relaxed);
        return CARD_NONE;
    }
    let was = LAST_INSERTED.swap(now, Ordering::Relaxed);
    if now == was {
        CARD_NONE
    } else if now {
        CARD_INSERTED
    } else {
        CARD_EJECTED
    }
}

/// Host: the same insert/eject edge-tracking algorithm as the device path
/// (above), calling `sd::is_inserted()` uniformly. `deluge_bsp::sd`'s host
/// stand-in always reports the backing file as present (`is_inserted()`
/// always returns `true`), so `now == was` holds on every poll after the
/// first — there is never an edge to report on host.
#[cfg(not(target_os = "none"))]
#[unsafe(no_mangle)]
pub extern "C" fn deluge_block_poll_card_event(unit: u8) -> DelugeCardEvent {
    if unit != 0 {
        return CARD_NONE;
    }
    static INITIALISED: AtomicBool = AtomicBool::new(false);
    static LAST_INSERTED: AtomicBool = AtomicBool::new(false);
    let now = sd::is_inserted();
    if !INITIALISED.swap(true, Ordering::Relaxed) {
        LAST_INSERTED.store(now, Ordering::Relaxed);
        return CARD_NONE;
    }
    let was = LAST_INSERTED.swap(now, Ordering::Relaxed);
    if now == was {
        CARD_NONE
    } else if now {
        CARD_INSERTED
    } else {
        CARD_EJECTED
    }
}
